from rob2_pipeline.methodology.types import Citation, DomainMethodology, ResponseRule, RuleCard

SUPP = "Sterne 2019 supplement"

DOMAIN3_METHODOLOGY = DomainMethodology(
    domain_id="D3",
    title="Bias due to missing outcome data",
    principles=["Imputed data count as missing outcome data for Q3.1.", "Time-to-event censoring before complete follow-up can represent missing outcome data."],
    rule_cards={
        "3.1": RuleCard("3.1", "Were data available for all, or nearly all, randomized participants?", {"Y": ResponseRule("Outcome data were available for all or enough participants that missing outcomes could not materially affect the result."), "PY": ResponseRule("Nearly all participants have data and missingness is unlikely to matter."), "PN": ResponseRule("Noticeable missing outcome data may affect the result."), "N": ResponseRule("A significant proportion of outcome data is missing or imputed."), "NI": ResponseRule("The extent of missing outcome data is not reported.")}, [Citation(SUPP, "p.18")]),
        "3.2": RuleCard("3.2", "Is there evidence that the result was not biased by missing outcome data?", {"Y": ResponseRule("Appropriate correction methods or sensitivity analyses convincingly show no material bias."), "PY": ResponseRule("Methods or sensitivity analyses suggest minimal impact with residual uncertainty."), "PN": ResponseRule("Methods are inadequate, limited, or poorly described."), "N": ResponseRule("No adequate attempt addresses missing-data bias or sensitivity analyses show possible bias."), "NA": ResponseRule("Not applicable if Q3.1 is Y/PY.")}, [Citation(SUPP, "p.18")]),
        "3.3": RuleCard("3.3", "Could missingness in the outcome depend on its true value?", {"Y": ResponseRule("Loss, withdrawal, or censoring is clearly related to health status or outcome."), "PY": ResponseRule("Reasons are ambiguous or could plausibly relate to true outcome value."), "PN": ResponseRule("Most documented reasons are unlikely to relate to true outcome value."), "N": ResponseRule("All missingness is clearly unrelated to outcome, such as technical failure or administrative interruption."), "NI": ResponseRule("Reasons or patterns are not described."), "NA": ResponseRule("Not applicable when Q3.2 is Y/PY.")}, [Citation(SUPP, "p.18")]),
        "3.4": RuleCard("3.4", "Is it likely that missingness depended on its true value?", {"Y": ResponseRule("Evidence such as differential missingness, outcome-related reasons, group-specific reasons, trial circumstances, or outcome-related censoring makes dependence likely."), "PY": ResponseRule("Some evidence suggests likely dependence on true outcome value."), "PN": ResponseRule("Reasons and patterns mostly argue against likely outcome dependence."), "N": ResponseRule("Evidence indicates missingness is independent of true outcome value or explained by measured characteristics."), "NI": ResponseRule("Insufficient information to judge likelihood."), "NA": ResponseRule("Not applicable when Q3.3 is N/PN.")}, [Citation(SUPP, "p.19")], notes=["For time-to-event analyses, censoring when participants stop or change assigned intervention for outcome-related reasons can make missingness likely dependent on its true value."]),
    },
)
