from rob2_pipeline.methodology.types import Citation, DomainMethodology, ResponseRule, RuleCard

SUPP = "Sterne 2019 supplement"

DOMAIN4_METHODOLOGY = DomainMethodology(
    domain_id="D4",
    title="Bias in measurement of the outcome",
    principles=["This domain concerns the method and process of outcome measurement, not whether the outcome is clinically ideal."],
    rule_cards={
        "4.1": RuleCard("4.1", "Was the method of measuring the outcome inappropriate?", {"Y": ResponseRule("The method is unsuitable, insensitive to plausible effects, or has poor validity."), "PY": ResponseRule("Strong indications suggest the method may be unsuitable or invalid."), "PN": ResponseRule("Method appears suitable with limited uncertainty."), "N": ResponseRule("Method is appropriate for the outcome."), "NI": ResponseRule("Insufficient information about the measurement method.")}, [Citation(SUPP, "p.22")]),
        "4.2": RuleCard("4.2", "Could measurement or ascertainment have differed between groups?", {"Y": ResponseRule("Measurement methods, thresholds, timing, or passive detection opportunities differed between groups."), "PY": ResponseRule("Differences in measurement, timing, or detection opportunities are plausible."), "PN": ResponseRule("Methods and timing appear comparable with minor uncertainty."), "N": ResponseRule("Same methods and thresholds were used at comparable time points."), "NI": ResponseRule("Insufficient information to determine comparability.")}, [Citation(SUPP, "p.22")], algorithm_note="Y/PY maps directly to high risk for Domain 4.", notes=["Q4.2 covers two types of differential ascertainment, and the distinction matters because Y/PY leads directly to High. Passive detection bias (answer Y/PY) occurs when one arm has more unscheduled clinical contacts than the other, creating additional opportunities for events to be passively identified during routine care. Active protocol-specified assessments (answer N/PN) occur when both arms undergo the same pre-specified outcome assessments, such as same imaging modality, same criteria, same protocol-defined schedule, but treatment-administration visit frequency happens to differ. Extra treatment visits are not additional outcome-assessment occasions when the measurement method, criteria, and schedule are identical. If the trial uses a pre-specified assessment protocol applied identically to both arms, answer N or PN even if one arm attends clinic more frequently for treatment administration."]),
        "4.3": RuleCard("4.3", "Were outcome assessors aware of intervention received?", {"Y": ResponseRule("Assessors were aware, blinding was impossible, or participants were assessors for participant-reported outcomes and knew assignment."), "PY": ResponseRule("Assessors probably knew assignment based on design or available evidence."), "PN": ResponseRule("Assessor blinding is likely but not verified."), "N": ResponseRule("Outcome assessors were blinded."), "NI": ResponseRule("Assessor awareness cannot be inferred from available evidence."), "NA": ResponseRule("Not applicable if Q4.1 or Q4.2 is Y/PY.")}, [Citation(SUPP, "p.22"), Citation("Sterne 2019 BMJ", "p.3")], notes=["Inference rule: If the trial is open-label (Q2.1=Y as shown in the context above) and the report contains no mention of a central blinded outcome adjudication committee or independent blinded assessors, answer PY (assessors likely aware of assignment) rather than NI. Reserve NI for cases where the blinding status of outcome assessors genuinely cannot be inferred, which is unusual once Q2.1=Y is established."]),
        "4.4": RuleCard("4.4", "Could assessment have been influenced by knowledge of intervention?", {"Y": ResponseRule("Outcome assessment clearly involves subjective judgment or participant report susceptible to knowledge of assignment."), "PY": ResponseRule("Assessment includes judgmental elements despite standardization."), "PN": ResponseRule("Outcome is mostly objective or safeguards leave little room for influence."), "N": ResponseRule("Outcome does not involve judgment and is not plausibly influenced by knowledge of assignment."), "NI": ResponseRule("Insufficient information about assessment process."), "NA": ResponseRule("Not applicable if assessors were unaware.")}, [Citation(SUPP, "p.22")], notes=["Knowledge can influence participant-reported outcomes, observer-reported outcomes involving judgment, and intervention-provider decision outcomes. It is unlikely to influence observer-reported outcomes that do not involve judgment, such as all-cause mortality.", "Answer N or PN when the outcome is physiologically determined, mechanically measured, centrally blinded, or otherwise not plausibly susceptible to assessor knowledge. For outcome assessments involving judgment, answer Y or PY unless explicit evidence shows the criteria and process are judgment-free."]),
        "4.5": RuleCard("4.5", "Is it likely assessment was influenced by knowledge of intervention?", {"Y": ResponseRule("Strong beliefs, expectations, or assessor involvement make influence likely."), "PY": ResponseRule("Moderate evidence suggests likely influence."), "PN": ResponseRule("Little evidence suggests likely influence; standard criteria or safeguards reduce concern."), "N": ResponseRule("No apparent mechanism or evidence of likely influence."), "NI": ResponseRule("Insufficient information about beliefs, expectations, or assessor role."), "NA": ResponseRule("Not applicable if Q4.4 is N/PN.")}, [Citation(SUPP, "p.23")], notes=['This question distinguishes "could have been influenced" (Some concerns when Q4.5=N/PN) from "likely was influenced" (High when Q4.5=Y/PY/NI). High requires strong levels of belief in either beneficial or harmful effects of the intervention, for example patient-reported symptoms in trials of homeopathy, or assessments of recovery by a physiotherapist who delivered the intervention. When standardized criteria are applied without evidence of strong beliefs, direct assessor involvement in delivering the intervention, or other mechanisms making influence likely, answer N or PN rather than Y or PY.']),
    },
)
