from rob2_pipeline.methodology.types import Citation, DomainMethodology, ResponseRule, RuleCard

SUPP = "Sterne 2019 supplement"

DOMAIN4_METHODOLOGY = DomainMethodology(
    domain_id="D4",
    title="Bias in measurement of the outcome",
    principles=["This domain concerns the method and process of outcome measurement, not whether the outcome is clinically ideal."],
    rule_cards={
        "4.1": RuleCard("4.1", "Was the method of measuring the outcome inappropriate?", {"Y": ResponseRule("The method is unsuitable, insensitive to plausible effects, or has poor validity."), "PY": ResponseRule("Strong indications suggest the method may be unsuitable or invalid."), "PN": ResponseRule("Method appears suitable with limited uncertainty."), "N": ResponseRule("Method is appropriate for the outcome."), "NI": ResponseRule("Insufficient information about the measurement method.")}, [Citation(SUPP, "p.22")]),
        "4.2": RuleCard("4.2", "Could measurement or ascertainment have differed between groups?", {"Y": ResponseRule("Measurement methods, thresholds, timing, or passive detection opportunities differed between groups."), "PY": ResponseRule("Differences in measurement, timing, or detection opportunities are plausible."), "PN": ResponseRule("Methods and timing appear comparable with minor uncertainty."), "N": ResponseRule("Same methods and thresholds were used at comparable time points."), "NI": ResponseRule("Insufficient information to determine comparability.")}, [Citation(SUPP, "p.22")], algorithm_note="Y/PY maps directly to high risk for Domain 4."),
        "4.3": RuleCard("4.3", "Were outcome assessors aware of intervention received?", {"Y": ResponseRule("Assessors were aware, blinding was impossible, or participants were assessors for participant-reported outcomes and knew assignment."), "PY": ResponseRule("Assessors probably knew assignment based on design or available evidence."), "PN": ResponseRule("Assessor blinding is likely but not verified."), "N": ResponseRule("Outcome assessors were blinded."), "NI": ResponseRule("Assessor awareness cannot be inferred from available evidence."), "NA": ResponseRule("Not applicable if Q4.1 or Q4.2 is Y/PY.")}, [Citation(SUPP, "p.22"), Citation("Sterne 2019 BMJ", "p.3")]),
        "4.4": RuleCard("4.4", "Could assessment have been influenced by knowledge of intervention?", {"Y": ResponseRule("Outcome assessment clearly involves subjective judgment or participant report susceptible to knowledge of assignment."), "PY": ResponseRule("Assessment includes judgmental elements despite standardization."), "PN": ResponseRule("Outcome is mostly objective or safeguards leave little room for influence."), "N": ResponseRule("Outcome does not involve judgment and is not plausibly influenced by knowledge of assignment."), "NI": ResponseRule("Insufficient information about assessment process."), "NA": ResponseRule("Not applicable if assessors were unaware.")}, [Citation(SUPP, "p.22")]),
        "4.5": RuleCard("4.5", "Is it likely assessment was influenced by knowledge of intervention?", {"Y": ResponseRule("Strong beliefs, expectations, or assessor involvement make influence likely."), "PY": ResponseRule("Moderate evidence suggests likely influence."), "PN": ResponseRule("Little evidence suggests likely influence; standard criteria or safeguards reduce concern."), "N": ResponseRule("No apparent mechanism or evidence of likely influence."), "NI": ResponseRule("Insufficient information about beliefs, expectations, or assessor role."), "NA": ResponseRule("Not applicable if Q4.4 is N/PN.")}, [Citation(SUPP, "p.23")]),
    },
)
